name: Continuous Deployment

on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [completed]
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "Wayne Van Son (Bot)"
          git config --global user.email "waynevanson@gmail.com"

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Create Version
        run: pnpm exec standard-version

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # assume this was tested during tests
      - name: Publish Docs
        run: |
          pnpm exec docs-ts
          git add --force docs/
          git commit -m 'chore: update docs [skip ci]' || true
          git push --tags
